// Event copy and workshop data, kept in sync with collectivebysoul.com.
export const copy = {
  tr: {
    "footer.postcardTitle": "Şehirden bir vapur uzaklıkta.",
    "footer.collageTitle": "Bir gün. Bir ada. Birlikte.",
    "footer.invitation": "Deniz yolculuğu, yeni karşılaşmalar ve kendine ayırdığın bir gün. Büyükada’da buluşalım.",
    "footer.watercolorAlt": "Büyükada kıyısının, tarihi iskelenin ve vapurun suluboya illüstrasyonu",
    "footer.collageAlt": "Büyükada’nın ahşap evlerini, bisikleti, çamları ve vapuru bir araya getiren kâğıt kolaj illüstrasyonu",
    "a11y.skip": "İçeriğe geç",
    "nav.day": "Gün",
    "nav.place": "Mekân",
    "nav.workshops": "Atölyeler",
    "nav.tickets": "Bilet",
    "nav.faq": "Sık sorulanlar",
    "nav.guest": "Biletim var",
    "a11y.language": "Dil seçimi",
    "nav.apply": "Katıl",
    "hero.eyebrow": "Chapter I · 19 Eylül 2026",
    "hero.title": "Leave the city behind.",
    "hero.body":
      "Otuz kişi, Büyükada’da denize açılan bir ev ve öğleden gece yarısına uzanan bir gün: atölyeler, havuz ve yemek.",
    "hero.primary": "Katıl",
    "hero.secondary": "Günün akışına bak",
    "facts.date": "19 Eylül",
    "facts.day": "Cumartesi",
    "facts.location": "İstanbul",
    "facts.people": "kişi",
    "intro.eyebrow": "Nasıl bir gün?",
    "intro.title": "Program hazır. Gün sana ait.",
    "intro.body":
      "Bu, sahne karşısında beklediğin bir festival değil. Bir atölyeye oturabilir, yarısında kalkıp havuza girebilir, tanımadığın biriyle resme başlayabilir ya da arka bahçede biraz sessiz kalabilirsin. Her şeyi yetiştirmeye çalışma. Merak ettiğin yerden gir.",
    "intro.joinTitle": "Katıl.",
    "intro.joinBody": "Bir şey yap, dene, ses çıkar, elini boyaya bulaştır.",
    "intro.meetTitle": "Karşılaş.",
    "intro.meetBody": "Aynı masaya otur, yeni bir sohbete yer aç.",
    "intro.paceTitle": "Kendi hızını bul.",
    "intro.paceBody": "Günün programı var; zorunlu bir rota yok.",
    "place.eyebrow": "Mekân",
    "place.title": "Denize açılan bir ev.",
    "place.body1":
      "Büyükada’daki villanın kapısı o gün yalnızca bize açık. Çamların altındaki havuz ve denize bakan bahçe gün boyunca seni bekliyor.",
    "place.body2":
      "Atölyeler evin farklı köşelerine yayılıyor. Havuz gün batımına kadar açık. Arka bahçe ise kalabalıktan kısa süreliğine uzaklaşmak isteyenlere ayrılmış durumda.",
    "place.stat1": "misafir",
    "place.stat2": "atölye ve açık alan",
    "gallery.label": "Mekân fotoğrafları",
    "flow.eyebrow": "Günün akışı",
    "flow.title": "Öğleden geceye, adada bir gün.",
    "flow.body":
      "Aradaki saatleri tek bir sahneye ya da sıraya bağlamadık. Gün üç kez yön değiştiriyor; kendi rotanı bu akışın içinde kuruyorsun.",
    "flow.s1t": "Başlıyoruz",
    "flow.s1b":
      "Büyükada’daki evde buluşuyoruz. Bahçeyi keşfet, yeni insanlarla tanış ve günün ritmine kendi hızında katıl.",
    "flow.s2t": "Bahçe · Havuz · Deniz",
    "flow.s2b":
      "Atölyeler, açık stüdyolar, havuz ve bar öğleden sonra evin farklı köşelerinde açılıyor. Bazı işler küçük gruplarla, bazıları uğrayıp devam edebileceğin şekilde ilerliyor.",
    "flow.s3t": "Geceye geçiyoruz",
    "flow.s3b":
      "Güneş denize inerken ışıklar yanıyor. Bahçede sohbetler uzuyor; günün son deneyimleri için yeniden bir araya geliyoruz.",
    "workshops.eyebrow": "Atölyeler ve deneyimler",
    "workshops.title": "İstediğine katıl.",
    "workshops.body":
      "Bazı atölyeler saatli ve sınırlı kontenjanlı, bazı stüdyolar gün boyunca açık. Katılımın kesinleştiğinde tercihlerini soracağız ve çakışmaları mümkün olduğunca birlikte çözeceğiz.",
    "hosts.eyebrow": "Kiminle yapıyoruz?",
    "hosts.title": "Her alanın başında işini yaşayan biri var.",
    "hosts.body":
      "Kalabalık bir sahne yerine küçük gruplar ve doğrudan temas istedik. Atölyeleri hazırlayan insanlar gün boyunca bizimle olacak.",
    "hosts.oguz": "Kolektif Ses",
    "hosts.seyma": "Koku Laboratuvarı",
    "hosts.deniz": "Stil İçgüdüdür",
    "music.eyebrow": "Günün müziği",
    "music.lead": "Müzik Tugen’den.",
    "music.body":
      "Bahçede, havuz kenarında ve atölyelerin arasında gün boyu sana eşlik edecek bir seçki. Öğleden sonra sakin başlayan akış, güneş batarken geceye doğru yükseliyor.",
    "tickets.eyebrow": "19 Eylül 2026",
    "tickets.title": "Bilet",
    "tickets.body":
      "Atölyeler ve birlikte geçireceğimiz bir gün tek bilete dahil.",
    "tickets.tag": "Günün tamamı dahil",
    "tickets.intro":
      "Büyükada’da bir ev, yaratıcı atölyeler ve öğleden geceye birlikte geçireceğimiz bir gün.",
    "tickets.cta": "Katıl",
    "tickets.includes": "Biletine dahil",
    "tickets.i1": "Tüm atölyelere erişim",
    "tickets.i2": "Bite Foods ikramları",
    "tickets.foodDetail": "Kişi başı 1 bun sandviç ve özel Japon tatlıları",
    "tickets.i3": "Kişi başı 2 içecek · alkollü veya alkolsüz",
    "tickets.i4": "Havuz ve bahçe kullanımı",
    "tickets.note": "Bar menüsündeki kokteyller bilete dahil değildir.",
    "guest.title": "Biletin hazır mı?",
    "guest.body": "Kişisel kodunla giriş yap; ulaşımını planla, atölyelerini seç.",
    "guest.cta": "Günümü planla",
    "apply.eyebrow": "Katılım",
    "apply.title": "Aramıza katıl.",
    "apply.body":
      "Referansın varsa bizimle paylaş. Yoksa yine de formu gönderebilirsin. Bu kısa form; evin kapasitesini, atölye gruplarını ve birlikte gelenleri planlamamıza yardımcı oluyor. Katılım talebine en geç 72 saat içinde sonraki adımlarla döneceğiz.",
    "form.name": "Ad soyad",
    "form.phone": "Telefon",
    "form.email": "E-posta",
    "form.instagram": "Instagram (isteğe bağlı)",
    "form.reference": "Bizi nereden duydun? / Referans",
    "form.party": "Kaç kişi geliyorsunuz?",
    "form.one": "Tek geliyorum",
    "form.two": "İki kişiyiz",
    "form.three": "Üç kişiyiz",
    "form.t1": "Etkinlik bilgilerini ve",
    "form.t2": "iptal koşullarını",
    "form.t3": "okudum, kabul ediyorum.",
    "form.note":
      "Başvurun Google Forms üzerinden ekibimize iletilir. 72 saat içinde sana döneceğiz. Bu işlem rezervasyon onayı değildir.",
    "form.submit": "Katıl",
    "faq.eyebrow": "Sık sorulanlar",
    "faq.title": "Gelmeden önce bilmen gerekenler.",
    "faq.q1": "Bilete tam olarak neler dahil?",
    "faq.a1":
      "Island Pass; tüm atölyeleri, Bite Foods’tan kişi başı 1 bun sandviç ve özel Japon tatlılarını, kişi başı alkollü veya alkolsüz 2 içeceği ve evin açık alanlarının kullanımını içerir. Bar menüsündeki kokteyller bilete dahil değildir.",
    "faq.q2": "Atölyelere nasıl kaydolacağım?",
    "faq.a2":
      "Katılımın kesinleştiğinde senden atölye tercihlerini isteyeceğiz. Kontenjanı sınırlı oturumları bu tercihlere göre planlayacağız. Açık stüdyolara gün içinde kayıt olmadan uğrayabilirsin.",
    "faq.q3": "Her atölyeye katılabilir miyim?",
    "faq.a3":
      "Bazı oturumlar çakışıyor veya sınırlı kontenjanla ilerliyor. Her şeyi yetiştirmek yerine en çok merak ettiğin alanları seçmeni öneriyoruz.",
    "faq.q4": "Yanıma ne almalıyım?",
    "faq.a4":
      "Mayo, havlu ve akşam serinliği için ince bir katman getir. Atölye malzemelerini biz hazırlıyoruz.",
    "faq.q5": "Tek başıma gelebilir miyim?",
    "faq.a5":
      "Evet. Gün boyunca küçük gruplar, ortak alanlar ve açık stüdyolar arasında hareket edeceğimiz için yeni insanlarla tanışmak için bolca alan var.",
    "faq.q6": "Neden kısa bir form dolduruyorum?",
    "faq.a6":
      "Çünkü burası büyük bir festival alanı değil, otuz kişilik özel bir ev. Form; evin kapasitesini, küçük atölye gruplarını ve katılımı doğru planlamamızı sağlıyor. Referansın varsa paylaşmanı istiyoruz; yoksa formu yine gönderebilirsin.",
    "faq.q7": "İptal koşulları nedir?",
    "faq.a7":
      "8 Eylül 2026’ya kadar yapılan iptallerde ücretin tamamını iade ediyoruz. Bu tarihten sonra biletini, bize önceden haber vererek başka birine devredebilirsin.",
    "faq.q8": "Evin açık adresi nedir?",
    "faq.a8":
      "Büyükada, İstanbul. Villanın açık adresini ve varış bilgisini onaylanan misafirlerle paylaşacağız.",
    "faq.q9": "Büyükada’ya ulaşımı nasıl sağlayabilirim?",
    "faq.a9start": "Büyükada’ya düzenlenen seferleri ve saatlerini ",
    "faq.a9link": "buradan",
    "faq.a9end": " inceleyebilirsiniz.",
    "faq.q10": "Grup olarak deniz taksiyle gelebilir miyiz?",
    "faq.a10":
      "Evet. Grubunuz için doğrudan evin iskelesine gelen özel deniz taksimizi ayarlayabiliriz. Kişi sayınızı ve gelmek istediğiniz saati bize önceden bildirmeniz yeterli. Dilerseniz İBB Deniz Taksi uygulamasından kendiniz de rezervasyon yapabilirsiniz. İBB Deniz Taksi Büyükada İskelesi’ne gelir; buradan eve ulaşımınızı kendiniz sağlamanız gerekir.",
    "closing.eyebrow": "19 Eylül 2026 · Büyükada",
    "closing.title": "Adada buluşalım.",
    "closing.body":
      "Katılım ya da programla ilgili aklına takılan bir şey varsa bize yaz. Gerçek bir insan cevap verecek.",
    "closing.cta": "Katıl",
    "footer.about":
      "Soul Collective, birlikte vakit geçirmenin daha iyi yollarını tasarlar. İlk buluşma: One Day on an Island · Chapter I.",
    "footer.explore": "Keşfet",
    "footer.event": "Etkinlik",
    "footer.date": "19 Eylül 2026, Cumartesi",
  },
  en: {
    "footer.postcardTitle": "A ferry ride away from the city.",
    "footer.collageTitle": "One day. One island. Together.",
    "footer.invitation": "A journey by sea, new connections, and a day to call your own. See you on Büyükada.",
    "footer.watercolorAlt": "Watercolor illustration of Büyükada’s waterfront, historic ferry terminal and passenger ferry",
    "footer.collageAlt": "Paper collage illustration of Büyükada’s timber villas, bicycle, pine trees and ferry",
    "a11y.skip": "Skip to content",
    "a11y.language": "Language selection",
    "nav.day": "The day",
    "nav.place": "The place",
    "nav.workshops": "Workshops",
    "nav.tickets": "Ticket",
    "nav.faq": "FAQ",
    "nav.guest": "Guest access",
    "nav.apply": "Join",
    "hero.eyebrow": "Chapter I · 19 September 2026",
    "hero.title": "Leave the city behind.",
    "hero.body":
      "Thirty people, a waterfront home on Büyükada, and a day stretching from afternoon past midnight: workshops, swimming and food.",
    "hero.primary": "Join",
    "hero.secondary": "See how the day unfolds",
    "facts.date": "19 September",
    "facts.day": "Saturday",
    "facts.location": "Istanbul",
    "facts.people": "people",
    "intro.eyebrow": "What kind of day?",
    "intro.title": "The programme is set. The day is yours.",
    "intro.body":
      "This is not a festival you watch from the edge. Sit down for a workshop, leave halfway for a swim, add to a painting someone else began, or disappear into the back garden for a quiet half-hour. Do not try to complete everything. Start wherever your curiosity takes you.",
    "intro.joinTitle": "Take part.",
    "intro.joinBody":
      "Make something, try something, make a sound, get paint on your hands.",
    "intro.meetTitle": "Meet.",
    "intro.meetBody":
      "Sit at the same table and leave room for an unexpected conversation.",
    "intro.paceTitle": "Move at your own pace.",
    "intro.paceBody":
      "There is a programme, but no compulsory route through it.",
    "place.eyebrow": "The place",
    "place.title": "A home opening onto the sea.",
    "place.body1":
      "The villa on Büyükada opens only for us that day. A pool under the pines and a garden facing the water await you throughout the day.",
    "place.body2":
      "Workshops unfold in different corners of the grounds. The pool stays open until sunset. The back garden is kept for anyone who wants a little distance from the crowd.",
    "place.stat1": "guests",
    "place.stat2": "workshops and open spaces",
    "gallery.label": "Photos of the venue",
    "flow.eyebrow": "The day",
    "flow.title": "An island day, from afternoon into the night.",
    "flow.body":
      "The hours in between are not tied to one stage or one running order. The day changes direction three times; you choose your route within it.",
    "flow.s1t": "We begin",
    "flow.s1b":
      "We meet at the house on Büyükada. Explore the garden, meet new people and settle into the day at your own pace.",
    "flow.s2t": "Garden · Pool · Sea",
    "flow.s2b":
      "Workshops, open studios, the pool and bar come alive across the grounds. Some sessions happen in small groups; others are spaces you can enter and leave in your own time.",
    "flow.s3t": "We move into the night",
    "flow.s3b":
      "As the sun reaches the water, the lights come on. Conversations linger in the garden as we gather for the final experiences of the day.",
    "workshops.eyebrow": "Workshops and experiences",
    "workshops.title": "Join what interests you.",
    "workshops.body":
      "Some workshops have fixed times and small capacities; other studios stay open all day. Once your place is confirmed, we will ask for your preferences and help untangle clashes where we can.",
    "hosts.eyebrow": "Who are we making it with?",
    "hosts.title": "Every space is held by someone who lives their practice.",
    "hosts.body":
      "We chose small groups and direct exchange over a crowded stage. The people who shaped the workshops will stay with us throughout the day.",
    "hosts.oguz": "Collective Sound",
    "hosts.seyma": "Fragrance Lab",
    "hosts.deniz": "Style Is Instinct",
    "music.eyebrow": "Music for the day",
    "music.lead": "Music by Tugen.",
    "music.body":
      "A selection that stays with you all day, across the garden, by the pool and between workshops. It begins gently in the afternoon and builds towards the night as the sun goes down.",
    "tickets.eyebrow": "19 September 2026",
    "tickets.title": "Ticket",
    "tickets.body":
      "One ticket for a day of workshops and time together.",
    "tickets.tag": "The full day included",
    "tickets.intro":
      "A home on Büyükada, creative workshops and a day together from afternoon into the night.",
    "tickets.cta": "Join",
    "tickets.includes": "Your ticket includes",
    "tickets.i1": "Access to all workshops",
    "tickets.i2": "Food by Bite Foods",
    "tickets.foodDetail": "1 bun sandwich per person and specialty Japanese desserts",
    "tickets.i3": "2 drinks per person · alcoholic or non-alcoholic",
    "tickets.i4": "Access to the pool and garden",
    "tickets.note": "Cocktails from the bar menu are not included.",
    "guest.title": "Already have your ticket?",
    "guest.body": "Use your personal code to plan your arrival and choose your workshops.",
    "guest.cta": "Plan my day",
    "apply.eyebrow": "Join",
    "apply.title": "Join us.",
    "apply.body":
      "If you have a reference, share it with us. If not, you can still send the form. This short form helps us plan the house capacity, workshop groups and guests arriving together. We will reply to your request within 72 hours with the next steps.",
    "form.name": "Full name",
    "form.phone": "Phone",
    "form.email": "Email",
    "form.instagram": "Instagram (optional)",
    "form.reference": "How did you hear about us? / Reference",
    "form.party": "How many are coming?",
    "form.one": "Just me",
    "form.two": "Two of us",
    "form.three": "Three of us",
    "form.t1": "I have read and accept the event information and",
    "form.t2": "cancellation terms",
    "form.t3": ".",
    "form.note":
      "Your application is sent to our team through Google Forms. We will reply within 72 hours. This is not a booking confirmation.",
    "form.submit": "Join",
    "faq.eyebrow": "FAQ",
    "faq.title": "What to know before you come.",
    "faq.q1": "What exactly is included?",
    "faq.a1":
      "Island Pass includes all workshops, 1 bun sandwich per person and specialty Japanese desserts by Bite Foods, 2 alcoholic or non-alcoholic drinks per person, and access to the house’s outdoor spaces. Cocktails from the bar menu are not included.",
    "faq.q2": "How do I reserve workshop places?",
    "faq.a2":
      "Once your place is confirmed, we will ask for your workshop preferences. We will plan limited-capacity sessions around those choices. You can enter the open studios at any point during the day without a reservation.",
    "faq.q3": "Can I attend every workshop?",
    "faq.a3":
      "Some sessions overlap or have limited capacity. We suggest choosing the ones you are most curious about rather than trying to complete everything.",
    "faq.q4": "What should I bring?",
    "faq.a4":
      "Bring swimwear, a towel and a light layer for the evening. We provide the workshop materials.",
    "faq.q5": "Can I come alone?",
    "faq.a5":
      "Yes. Small groups, shared spaces and open studios create plenty of natural ways to meet people throughout the day.",
    "faq.q6": "Why do I fill out a short form?",
    "faq.a6":
      "Because this is a thirty-person private home, not a large festival ground. The form helps us plan the house, small workshop groups and attendance properly. If you have a reference, we ask you to share it; if not, you can still send the form.",
    "faq.q7": "What is the cancellation policy?",
    "faq.a7":
      "Cancellations made by 8 September 2026 receive a full refund. After that, you may transfer your ticket to someone else with advance notice.",
    "faq.q8": "What is the exact address?",
    "faq.a8":
      "Büyükada, Istanbul. We share the villa’s exact address and arrival information with confirmed guests.",
    "faq.q9": "How can I get to Büyükada?",
    "faq.a9start": "You can check ferry routes and departure times to Büyükada ",
    "faq.a9link": "here",
    "faq.a9end": ".",
    "faq.q10": "Can we arrive as a group by sea taxi?",
    "faq.a10":
      "Yes. We can arrange our private sea taxi for your group, arriving directly at the house’s pier. Simply let us know your group size and preferred arrival time in advance. You can also book independently through the İBB Deniz Taksi app. This service arrives at Büyükada Pier; you will need to make your own way to the house from there.",
    "closing.eyebrow": "19 September 2026 · Büyükada",
    "closing.title": "Meet us on the island.",
    "closing.body":
      "If you have a question about joining or the programme, write to us. A real person will answer.",
    "closing.cta": "Join",
    "footer.about":
      "Soul Collective designs better ways to spend time together. First gathering: One Day on an Island · Chapter I.",
    "footer.explore": "Explore",
    "footer.event": "The event",
    "footer.date": "Saturday, 19 September 2026",
  },
};

export const workshops = {
  tr: [
    {
      i: "web/w2.webp",
      t: "Kolektif Ses",
      h: "Dr. Oğuz Öner",
      m: "15:00–16:15 · 12 kişi",
      mm: "75 dakika · 12 kişi · Köşk ve çevresi",
      s: "Önce adayı dinliyoruz. Sonra duyduklarımızı ses, nefes ve ritimle birlikte çalıyoruz.",
      b: "Büyükada nasıl ses çıkarıyor? Köşkün çevresinde kısa bir ses yürüyüşüne çıkıp rüzgârı, suyu, kuşları ve birbirimizi dinleyeceğiz. Ardından Dr. Oğuz Öner’in yönlendirdiği Soundpainting yöntemiyle bu sesleri anlık bir bestede buluşturacağız. Müzik bilgisi gerekmiyor; dinlemeye ve ses çıkarmaya açık olman yeterli.",
    },
    {
      i: "web/w3.webp",
      t: "Koku Laboratuvarı",
      h: "Şeyma Çavdur",
      m: "16:30–18:00 · 12 kişi",
      mm: "90 dakika · 12 kişi · Arka bahçe",
      s: "Koku hafızasından parfüm tasarımına; sonunda kendi hazırladığın şişe seninle geliyor.",
      b: "Şeyma Çavdur’la kokunun hafızada nasıl yer ettiğine, burnun nasıl çalıştığına ve bir parfümün nasıl kurulduğuna bakacağız. Farklı notaları tek tek deneyip kendi koku haritanı çıkaracak, ardından sana ait küçük bir parfüm hazırlayacaksın.",
    },
    {
      i: "web/w5.webp",
      t: "Stil İçgüdüdür",
      h: "Deniz Mısır",
      m: "18:00–19:00 · 12 kişi",
      mm: "60 dakika · 12 kişi · Çim alan",
      s: "Düşünmeden seçtiğin renk, doku ve parçalar sana ne söylüyor?",
      b: "Bu bir “doğru giyinme” dersi değil. Deniz Mısır seni görseller, dokular ve aksesuarlar arasında hızlı seçimler yapmaya davet edecek. Sonra o seçimde neyin seni çektiğine bakacak ve bulduğun ipucunu kendi görünüşünde tek bir dokunuşa çevireceksin.",
    },
    {
      i: "web/w6.webp",
      t: "Fortune Dome",
      h: "Birebir deneyim",
      m: "16:30–17:30 · 21:15–22:15",
      mm: "15 dakika · Birebir · Bahçe",
      s: "Bahçede küçük bir çadır. İçeride ne olduğunu önceden anlatmıyoruz.",
      b: "Fortune Dome gün ışığında ve gece olmak üzere iki kez açılıyor. Girişte listeden bir saat seçiyor ve vaktin geldiğinde içeri tek başına giriyorsun. On beş dakika yalnızca sana ait. Geri kalanını içeride öğrenirsin.",
    },
    {
      i: "web/w7.webp",
      t: "Doğal Boyama",
      h: "Açık stüdyo",
      m: "Gün boyunca · kendi hızında",
      mm: "Gün boyunca · Açık stüdyo · Bahçe",
      s: "Katla, bağla, boyaya bırak. Son sözü doğal pigmentler söylesin.",
      b: "Gün boyunca açık olan bu stüdyoda kumaşını ve renklerini seçip katlama ve bağlama tekniklerini deneyeceksin. Pigmentin kumaşta bırakacağı izi bütünüyle kontrol edemezsin; zaten her parçayı tek yapan da bu.",
    },
    {
      i: "web/w8.webp",
      t: "Serbest Resim",
      h: "Açık stüdyo",
      m: "Gün boyunca · kendi hızında",
      mm: "Gün boyunca · Açık stüdyo · Veranda",
      s: "Verandada tuval, boya ve fırçalar var. Beş dakika kal ya da bir saat.",
      b: "Bir tema ya da bitirme zorunluluğu yok. Bir iz bırakabilir, başka birinin başladığı resme devam edebilir ya da tuvalin başında yalnız kalabilirsin. Gün bittiğinde ortaya kimin yaptığı belli olmayan ortak işler çıkabilir.",
    },
  ],
  en: [
    {
      i: "web/w2.webp",
      t: "Collective Sound",
      h: "Dr Oğuz Öner",
      m: "15:00–16:15 · 12 people",
      mm: "75 minutes · 12 people · House and surroundings",
      s: "First we listen to the island. Then we play what we heard with voice, breath and rhythm.",
      b: "What does Büyükada sound like? We will take a short sound walk around the house, listening to the wind, water, birds and one another. Then Dr Oğuz Öner will guide us through Soundpainting, weaving those sounds into a live, one-off composition. You do not need musical training—only a willingness to listen and make a sound.",
    },
    {
      i: "web/w3.webp",
      t: "Fragrance Lab",
      h: "Şeyma Çavdur",
      m: "16:30–18:00 · 12 people",
      mm: "90 minutes · 12 people · Back garden",
      s: "From scent memory to perfume composition, with your own bottle to take home.",
      b: "With Şeyma Çavdur, we will look at how scent settles into memory, how the nose works and how a perfume is built. You will explore individual notes, map your own scent memory and compose a small fragrance of your own.",
    },
    {
      i: "web/w5.webp",
      t: "Style Is Instinct",
      h: "Deniz Mısır",
      m: "18:00–19:00 · 12 people",
      mm: "60 minutes · 12 people · Lawn",
      s: "What do the colours, textures and pieces you choose without thinking say about you?",
      b: "This is not a lesson in dressing correctly. Deniz Mısır invites you to make quick choices between images, textures and accessories, then notice what drew you in. You will turn that clue into one small intervention in your own look.",
    },
    {
      i: "web/w6.webp",
      t: "Fortune Dome",
      h: "One-to-one experience",
      m: "16:30–17:30 · 21:15–22:15",
      mm: "15 minutes · One-to-one · Garden",
      s: "A small tent in the garden. We are not telling you what happens inside.",
      b: "Fortune Dome opens twice, once in daylight and once after dark. Choose a time from the list at the entrance and return when it is your turn. You go in alone. Those fifteen minutes are yours; you will discover the rest inside.",
    },
    {
      i: "web/w7.webp",
      t: "Natural Dyeing",
      h: "Open studio",
      m: "All day · at your own pace",
      mm: "All day · Open studio · Garden",
      s: "Fold it, bind it, leave it in the dye. Let natural pigments have the final word.",
      b: "This open studio runs throughout the day. Choose your cloth and colours, then experiment with folding and binding before lowering your piece into the dye. The mark cannot be fully controlled—that is what makes each result singular.",
    },
    {
      i: "web/w8.webp",
      t: "Free Painting",
      h: "Open studio",
      m: "All day · at your own pace",
      mm: "All day · Open studio · Veranda",
      s: "Canvas, paint and brushes are waiting on the veranda. Stay for five minutes or an hour.",
      b: "There is no theme and nothing has to be finished. Leave one mark, continue a painting somebody else began, or spend time alone with a canvas. By the end of the day, we may have works that belong to no single person.",
    },
  ],
};
