// Event copy and photography preserved from the latest event landing page.
export const copy = {
  tr: {
    "a11y.skip": "İçeriğe geç",
    "nav.day": "Gün",
    "nav.place": "Mekân",
    "nav.workshops": "Atölyeler",
    "nav.music": "Müzik",
    "nav.tickets": "Bilet",
    "nav.faq": "Sık sorulanlar",
    "a11y.language": "Dil seçimi",
    "nav.apply": "Katıl",
    "hero.eyebrow": "Chapter I · The Crossing · 19 Eylül 2026",
    "hero.title": "Leave the city behind.",
    "hero.body":
      "Elli kişi, Büyükada’da denize açılan bir ev ve öğleden gece yarısına uzanan bir gün: atölyeler, havuz, müzik, yemek ve deniz yolculuğu.",
    "hero.primary": "Katıl",
    "hero.secondary": "Günün akışına bak",
    "facts.date": "19 Eylül",
    "facts.day": "Cumartesi",
    "facts.departure": "Karaköy · Kadıköy",
    "facts.people": "kişi",
    "facts.return": "dönüş",
    "intro.eyebrow": "Nasıl bir gün?",
    "intro.title": "Program hazır. Gün sana ait.",
    "intro.body":
      "Bu, sahne karşısında beklediğin bir festival değil. Bir atölyeye oturabilir, yarısında kalkıp havuza girebilir, tanımadığın biriyle resme başlayabilir ya da arka bahçede biraz sessiz kalabilirsin. Her şeyi yetiştirmeye çalışma. Merak ettiğin yerden gir.",
    "intro.joinTitle": "Katıl.",
    "intro.joinBody": "Bir şey yap, dene, ses çıkar, elini boyaya bulaştır.",
    "intro.meetTitle": "Karşılaş.",
    "intro.meetBody": "Aynı tekneye bin, yeni bir sohbete yer aç.",
    "intro.paceTitle": "Kendi hızını bul.",
    "intro.paceBody": "Günün programı var; zorunlu bir rota yok.",
    "place.eyebrow": "Mekân",
    "place.title": "Denize açılan bir ev.",
    "place.body1":
      "Büyükada’daki villanın kapısı o gün yalnızca bize açık. Tekne evin iskelesine yanaşıyor; birkaç adım sonra çamların altındaki havuza, taş kayıkhaneye ve denize bakan bahçeye çıkıyorsun.",
    "place.body2":
      "Atölyeler evin farklı köşelerine yayılıyor. Havuz gün batımına kadar açık. Arka bahçe ise müzikten ve kalabalıktan kısa süreliğine uzaklaşmak isteyenlere ayrılmış durumda.",
    "place.stat1": "misafir",
    "place.stat2": "atölye ve açık alan",
    "place.stat3": "saat, tekneden tekneye",
    "gallery.label": "Mekân ve tekne fotoğrafları",
    "flow.eyebrow": "Günün akışı",
    "flow.title": "Öğlen İstanbul’dan çıkıyoruz. Gece yarısı dönüyoruz.",
    "flow.body":
      "Aradaki saatleri tek bir sahneye ya da sıraya bağlamadık. Gün üç kez yön değiştiriyor; kendi rotanı bu akışın içinde kuruyorsun.",
    "flow.s1t": "Başlıyoruz",
    "flow.s1b":
      "Özel tekne 12:30’da Karaköy’den, 13:00’te Kadıköy’den hareket ediyor. Şehir arkamızda kalırken ilk set başlıyor; doğrudan evin iskelesine yanaşıyoruz.",
    "flow.s2t": "Bahçe · Havuz · Deniz",
    "flow.s2b":
      "Atölyeler, açık stüdyolar, havuz ve bar öğleden sonra evin farklı köşelerinde açılıyor. Bazı işler küçük gruplarla, bazıları uğrayıp devam edebileceğin şekilde ilerliyor.",
    "flow.s3t": "Geceye geçiyoruz",
    "flow.s3b":
      "Güneş denize inerken ışıklar yanıyor. Müzik akşamla birlikte yükseliyor ve gece setine dönüyor. Dönüş teknesi 00:30’da iskeleden ayrılıyor.",
    "workshops.eyebrow": "Atölyeler ve deneyimler",
    "workshops.title": "İstediğine katıl.",
    "workshops.body":
      "Bazı atölyeler saatli ve sınırlı kontenjanlı, bazı stüdyolar gün boyunca açık. Katılımın kesinleştiğinde tercihlerini soracağız ve çakışmaları mümkün olduğunca birlikte çözeceğiz.",
    "hosts.eyebrow": "Kiminle yapıyoruz?",
    "hosts.title": "Her alanın başında işini yaşayan biri var.",
    "hosts.body":
      "Kalabalık bir sahne yerine küçük gruplar ve doğrudan temas istedik. Atölyeleri hazırlayan insanlar gün boyunca bizimle olacak.",
    "hosts.oguz": "Kolektif Ses",
    "hosts.seyma": "Koku Laboratuvarı",
    "hosts.bisou": "Stil İçgüdüdür",
    "music.time": "16:30–00:00",
    "music.title": "Müzik",
    "music.tba": "Line-up TBA",
    "music.djs": "DJ'ler",
    "music.order": "A–Z",
    "music.listLabel": "DJ'ler, alfabetik sıra",
    "tickets.eyebrow": "19 Eylül 2026",
    "tickets.title": "Bilet",
    "tickets.body":
      "Tekne yolculuğundan gece dönüşüne kadar günün tamamı tek bilete dahil.",
    "tickets.tag": "Günün tamamı dahil",
    "tickets.intro":
      "Karaköy ya da Kadıköy’den birlikte çıkıyor, doğrudan evin iskelesine varıyor ve gece aynı teknede dönüyoruz.",
    "tickets.cta": "Katıl",
    "tickets.includes": "Biletine dahil",
    "tickets.i1": "Karaköy veya Kadıköy’den özel tekneyle gidiş",
    "tickets.i2": "00:30’da özel tekneyle dönüş",
    "tickets.i3": "Tüm atölyelere erişim",
    "tickets.i4": "Bite Foods tarafından hazırlanan ikramlar",
    "tickets.i5": "Alkollü ve alkolsüz ortak servis içecekleri",
    "tickets.i6": "Havuz, bahçe, kayıkhane ve iskele kullanımı",
    "tickets.note": "Bar menüsündeki kokteyller bilete dahil değildir.",
    "apply.eyebrow": "Katılım",
    "apply.title": "Aramıza katıl.",
    "apply.body":
      "Referansın varsa bizimle paylaş. Yoksa yine de formu gönderebilirsin. Bu kısa form; evin kapasitesini, atölye gruplarını ve birlikte gelenleri planlamamıza yardımcı oluyor. Katılım talebine en geç 72 saat içinde sonraki adımlarla döneceğiz.",
    "form.name": "Ad soyad",
    "form.phone": "Telefon",
    "form.email": "E-posta",
    "form.instagram": "Instagram (isteğe bağlı)",
    "form.reference": "Bizi nereden duydun? / Referans",
    "form.party": "Kaç kişi geliyorsunuz?",
    "form.one": "Tek geliyorum",
    "form.two": "İki kişiyiz",
    "form.three": "Üç kişiyiz",
    "form.t1": "Etkinlik bilgilerini ve",
    "form.t2": "iptal koşullarını",
    "form.t3": "okudum, kabul ediyorum.",
    "form.note":
      "Başvurun Google Forms üzerinden ekibimize iletilir. 72 saat içinde sana döneceğiz. Bu işlem rezervasyon onayı değildir.",
    "form.submit": "Katıl",
    "faq.eyebrow": "Sık sorulanlar",
    "faq.title": "Gelmeden önce bilmen gerekenler.",
    "faq.q1": "Bilete tam olarak neler dahil?",
    "faq.a1":
      "The Crossing Pass; Karaköy veya Kadıköy’den özel tekneyle gidiş ve 00:30’da dönüşün yanı sıra tüm atölyeleri, Bite Foods ikramlarını, ortak servis içeceklerini ve evin açık alanlarının kullanımını içerir. Bar menüsündeki kokteyller bilete dahil değildir.",
    "faq.q2": "Tekneyi kaçırırsam ne olur?",
    "faq.a2":
      "Vapurla Büyükada’ya gelip eve kendi imkânınla ulaşabilirsin; ancak açılışı ve tekne deneyimini kaçırmış olursun. Kalkış saatleri kesin: Karaköy 12:30, Kadıköy 13:00.",
    "faq.q3": "Atölyelere nasıl kaydolacağım?",
    "faq.a3":
      "Katılımın kesinleştiğinde senden atölye tercihlerini isteyeceğiz. Kontenjanı sınırlı oturumları bu tercihlere göre planlayacağız. Açık stüdyolara gün içinde kayıt olmadan uğrayabilirsin.",
    "faq.q4": "Her atölyeye katılabilir miyim?",
    "faq.a4":
      "Bazı oturumlar çakışıyor veya sınırlı kontenjanla ilerliyor. Her şeyi yetiştirmek yerine en çok merak ettiğin alanları seçmeni öneriyoruz.",
    "faq.q5": "Yanıma ne almalıyım?",
    "faq.a5":
      "Mayo, havlu ve akşam serinliği için ince bir katman getir. Atölye malzemelerini biz hazırlıyoruz.",
    "faq.q6": "Tek başıma gelebilir miyim?",
    "faq.a6":
      "Evet. Gün boyunca küçük gruplar, ortak alanlar ve açık stüdyolar arasında hareket edeceğimiz için yeni insanlarla tanışmak için bolca alan var.",
    "faq.q7": "Neden kısa bir form dolduruyorum?",
    "faq.a7":
      "Çünkü burası büyük bir festival alanı değil, elli kişilik özel bir ev. Form; evin kapasitesini, küçük atölye gruplarını ve ulaşımı doğru planlamamızı sağlıyor. Referansın varsa paylaşmanı istiyoruz; yoksa formu yine gönderebilirsin.",
    "faq.q8": "İptal koşulları nedir?",
    "faq.a8":
      "8 Eylül 2026’ya kadar yapılan iptallerde ücretin tamamını iade ediyoruz. Bu tarihten sonra biletini, bize önceden haber vererek başka birine devredebilirsin.",
    "faq.q9": "Evin açık adresi nedir?",
    "faq.a9":
      "Büyükada, İstanbul. Villanın açık adresini ve varış bilgisini onaylanan misafirlerle paylaşacağız.",
    "closing.eyebrow": "19 Eylül 2026 · Büyükada",
    "closing.title": "İskelede buluşalım.",
    "closing.body":
      "Katılım ya da programla ilgili aklına takılan bir şey varsa bize yaz. Gerçek bir insan cevap verecek.",
    "closing.cta": "Katıl",
    "footer.about":
      "Soul Collective, birlikte vakit geçirmenin daha iyi yollarını tasarlar. İlk buluşma: One Day on an Island · Chapter I: The Crossing.",
    "footer.explore": "Keşfet",
    "footer.event": "Etkinlik",
    "footer.date": "19 Eylül 2026, Cumartesi",
    "footer.boat": "Karaköy 12:30 · Kadıköy 13:00",
    "footer.return": "Dönüş 00:30",
  },
  en: {
    "a11y.skip": "Skip to content",
    "a11y.language": "Language selection",
    "nav.day": "The day",
    "nav.place": "The place",
    "nav.workshops": "Workshops",
    "nav.music": "Music",
    "nav.tickets": "Ticket",
    "nav.faq": "FAQ",
    "nav.apply": "Join",
    "hero.eyebrow": "Chapter I · The Crossing · 19 September 2026",
    "hero.title": "Leave the city behind.",
    "hero.body":
      "Fifty people, a waterfront home on Büyükada, and a day stretching from afternoon past midnight: workshops, swimming, music, food and a journey across the water.",
    "hero.primary": "Join",
    "hero.secondary": "See how the day unfolds",
    "facts.date": "19 September",
    "facts.day": "Saturday",
    "facts.departure": "Karaköy · Kadıköy",
    "facts.people": "people",
    "facts.return": "return",
    "intro.eyebrow": "What kind of day?",
    "intro.title": "The programme is set. The day is yours.",
    "intro.body":
      "This is not a festival you watch from the edge. Sit down for a workshop, leave halfway for a swim, add to a painting someone else began, or disappear into the back garden for a quiet half-hour. Do not try to complete everything. Start wherever your curiosity takes you.",
    "intro.joinTitle": "Take part.",
    "intro.joinBody":
      "Make something, try something, make a sound, get paint on your hands.",
    "intro.meetTitle": "Meet.",
    "intro.meetBody":
      "Board the same boat and leave room for an unexpected conversation.",
    "intro.paceTitle": "Move at your own pace.",
    "intro.paceBody":
      "There is a programme, but no compulsory route through it.",
    "place.eyebrow": "The place",
    "place.title": "A home opening onto the sea.",
    "place.body1":
      "The villa on Büyükada opens only for us that day. The boat arrives at the house pier; a few steps take you to a pool under the pines, a stone boathouse and a garden facing the water.",
    "place.body2":
      "Workshops unfold in different corners of the grounds. The pool stays open until sunset. The back garden is kept for anyone who wants a little distance from the music and the crowd.",
    "place.stat1": "guests",
    "place.stat2": "workshops and open spaces",
    "place.stat3": "hours, boat to boat",
    "gallery.label": "Photos of the venue and boat",
    "flow.eyebrow": "The day",
    "flow.title": "We leave Istanbul at noon. We return after midnight.",
    "flow.body":
      "The hours in between are not tied to one stage or one running order. The day changes direction three times; you choose your route within it.",
    "flow.s1t": "We begin",
    "flow.s1b":
      "Our private boat leaves Karaköy at 12:30 and Kadıköy at 13:00. The first set begins as the city falls behind us, and we arrive directly at the house pier.",
    "flow.s2t": "Garden · Pool · Sea",
    "flow.s2b":
      "Workshops, open studios, the pool and bar come alive across the grounds. Some sessions happen in small groups; others are spaces you can enter and leave in your own time.",
    "flow.s3t": "We move into the night",
    "flow.s3b":
      "As the sun reaches the water, the lights come on. The music rises with the evening and turns into the night set. The return boat leaves the pier at 00:30.",
    "workshops.eyebrow": "Workshops and experiences",
    "workshops.title": "Join what interests you.",
    "workshops.body":
      "Some workshops have fixed times and small capacities; other studios stay open all day. Once your place is confirmed, we will ask for your preferences and help untangle clashes where we can.",
    "hosts.eyebrow": "Who are we making it with?",
    "hosts.title": "Every space is held by someone who lives their practice.",
    "hosts.body":
      "We chose small groups and direct exchange over a crowded stage. The people who shaped the workshops will stay with us throughout the day.",
    "hosts.oguz": "Collective Sound",
    "hosts.seyma": "Fragrance Lab",
    "hosts.bisou": "Style Is Instinct",
    "music.time": "16:30–00:00",
    "music.title": "Music",
    "music.tba": "Line-up TBA",
    "music.djs": "DJs",
    "music.order": "A–Z",
    "music.listLabel": "DJs, alphabetical order",
    "tickets.eyebrow": "19 September 2026",
    "tickets.title": "Ticket",
    "tickets.body":
      "From the boat journey to the late-night return, the full day is included in one ticket.",
    "tickets.tag": "The full day included",
    "tickets.intro":
      "We leave together from Karaköy or Kadıköy, arrive directly at the house pier and return on the same boat after midnight.",
    "tickets.cta": "Join",
    "tickets.includes": "Your ticket includes",
    "tickets.i1": "Private boat outbound from Karaköy or Kadıköy",
    "tickets.i2": "Private boat return at 00:30",
    "tickets.i3": "Access to all workshops",
    "tickets.i4": "Food prepared by Bite Foods",
    "tickets.i5": "Shared alcoholic and non-alcoholic drinks",
    "tickets.i6": "Access to the pool, garden, boathouse and pier",
    "tickets.note": "Cocktails from the bar menu are not included.",
    "apply.eyebrow": "Join",
    "apply.title": "Join us.",
    "apply.body":
      "If you have a reference, share it with us. If not, you can still send the form. This short form helps us plan the house capacity, workshop groups and guests arriving together. We will reply to your request within 72 hours with the next steps.",
    "form.name": "Full name",
    "form.phone": "Phone",
    "form.email": "Email",
    "form.instagram": "Instagram (optional)",
    "form.reference": "How did you hear about us? / Reference",
    "form.party": "How many are coming?",
    "form.one": "Just me",
    "form.two": "Two of us",
    "form.three": "Three of us",
    "form.t1": "I have read and accept the event information and",
    "form.t2": "cancellation terms",
    "form.t3": ".",
    "form.note":
      "Your application is sent to our team through Google Forms. We will reply within 72 hours. This is not a booking confirmation.",
    "form.submit": "Join",
    "faq.eyebrow": "FAQ",
    "faq.title": "What to know before you come.",
    "faq.q1": "What exactly is included?",
    "faq.a1":
      "The Crossing Pass includes the private boat from Karaköy or Kadıköy and the 00:30 return, plus all workshops, food by Bite Foods, shared drinks and access to the house’s outdoor spaces. Cocktails from the bar menu are not included.",
    "faq.q2": "What if I miss the boat?",
    "faq.a2":
      "You can take a public ferry to Büyükada and make your own way to the house, but you will miss the opening and the boat experience. Departure times are fixed: 12:30 from Karaköy and 13:00 from Kadıköy.",
    "faq.q3": "How do I reserve workshop places?",
    "faq.a3":
      "Once your place is confirmed, we will ask for your workshop preferences. We will plan limited-capacity sessions around those choices. You can enter the open studios at any point during the day without a reservation.",
    "faq.q4": "Can I attend every workshop?",
    "faq.a4":
      "Some sessions overlap or have limited capacity. We suggest choosing the ones you are most curious about rather than trying to complete everything.",
    "faq.q5": "What should I bring?",
    "faq.a5":
      "Bring swimwear, a towel and a light layer for the evening. We provide the workshop materials.",
    "faq.q6": "Can I come alone?",
    "faq.a6":
      "Yes. Small groups, shared spaces and open studios create plenty of natural ways to meet people throughout the day.",
    "faq.q7": "Why do I fill out a short form?",
    "faq.a7":
      "Because this is a fifty-person private home, not a large festival ground. The form helps us plan the house, small workshop groups and transport properly. If you have a reference, we ask you to share it; if not, you can still send the form.",
    "faq.q8": "What is the cancellation policy?",
    "faq.a8":
      "Cancellations made by 8 September 2026 receive a full refund. After that, you may transfer your ticket to someone else with advance notice.",
    "faq.q9": "What is the exact address?",
    "faq.a9":
      "Büyükada, Istanbul. We share the villa’s exact address and arrival information with confirmed guests.",
    "closing.eyebrow": "19 September 2026 · Büyükada",
    "closing.title": "Meet us at the pier.",
    "closing.body":
      "If you have a question about joining or the programme, write to us. A real person will answer.",
    "closing.cta": "Join",
    "footer.about":
      "Soul Collective designs better ways to spend time together. First gathering: One Day on an Island · Chapter I: The Crossing.",
    "footer.explore": "Explore",
    "footer.event": "The event",
    "footer.date": "Saturday, 19 September 2026",
    "footer.boat": "Karaköy 12:30 · Kadıköy 13:00",
    "footer.return": "Return at 00:30",
  },
};

export const workshops = {
  tr: [
    {
      i: "web/w2.webp",
      t: "Kolektif Ses",
      h: "Dr. Oğuz Öner",
      m: "15:00–16:15 · 15 kişi",
      mm: "75 dakika · 15 kişi · Köşk ve çevresi",
      s: "Önce adayı dinliyoruz. Sonra duyduklarımızı ses, nefes ve ritimle birlikte çalıyoruz.",
      b: "Büyükada nasıl ses çıkarıyor? Köşkün çevresinde kısa bir ses yürüyüşüne çıkıp rüzgârı, suyu, kuşları ve birbirimizi dinleyeceğiz. Ardından Dr. Oğuz Öner’in yönlendirdiği Soundpainting yöntemiyle bu sesleri anlık bir bestede buluşturacağız. Müzik bilgisi gerekmiyor; dinlemeye ve ses çıkarmaya açık olman yeterli.",
      w: 1080,
      hh: 1350,
    },
    {
      i: "web/w3.webp",
      t: "Koku Laboratuvarı",
      h: "Şeyma Çavdur",
      m: "16:30–18:00 · 10 kişi",
      mm: "90 dakika · 10 kişi · Arka bahçe",
      s: "Koku hafızasından parfüm tasarımına; sonunda kendi hazırladığın şişe seninle geliyor.",
      b: "Şeyma Çavdur’la kokunun hafızada nasıl yer ettiğine, burnun nasıl çalıştığına ve bir parfümün nasıl kurulduğuna bakacağız. Farklı notaları tek tek deneyip kendi koku haritanı çıkaracak, ardından sana ait küçük bir parfüm hazırlayacaksın.",
      w: 1760,
      hh: 2200,
    },
    {
      i: "web/w5.webp",
      t: "Stil İçgüdüdür",
      h: "Bisou Me",
      m: "18:00–19:00 · açık katılım",
      mm: "60 dakika · Açık katılım · Çim alan",
      s: "Düşünmeden seçtiğin renk, doku ve parçalar sana ne söylüyor?",
      b: "Bu bir “doğru giyinme” dersi değil. Bisou Me seni görseller, dokular ve aksesuarlar arasında hızlı seçimler yapmaya davet edecek. Sonra o seçimde neyin seni çektiğine bakacak ve bulduğun ipucunu kendi görünüşünde tek bir dokunuşa çevireceksin.",
      w: 800,
      hh: 600,
    },
    {
      i: "web/w6.webp",
      t: "Fortune Dome",
      h: "Birebir deneyim",
      m: "16:30–17:30 · 21:15–22:15",
      mm: "15 dakika · Birebir · Bahçe",
      s: "Bahçede küçük bir çadır. İçeride ne olduğunu önceden anlatmıyoruz.",
      b: "Fortune Dome gün ışığında ve gece olmak üzere iki kez açılıyor. Girişte listeden bir saat seçiyor ve vaktin geldiğinde içeri tek başına giriyorsun. On beş dakika yalnızca sana ait. Geri kalanını içeride öğrenirsin.",
      w: 1122,
      hh: 1402,
    },
    {
      i: "web/w7.webp",
      t: "Doğal Boyama",
      h: "Açık stüdyo",
      m: "Gün boyunca · kendi hızında",
      mm: "Gün boyunca · Açık stüdyo · Bahçe",
      s: "Katla, bağla, boyaya bırak. Son sözü doğal pigmentler söylesin.",
      b: "Gün boyunca açık olan bu stüdyoda kumaşını ve renklerini seçip katlama ve bağlama tekniklerini deneyeceksin. Pigmentin kumaşta bırakacağı izi bütünüyle kontrol edemezsin; zaten her parçayı tek yapan da bu.",
      w: 1760,
      hh: 2200,
    },
    {
      i: "web/w8.webp",
      t: "Serbest Resim",
      h: "Açık stüdyo",
      m: "Gün boyunca · kendi hızında",
      mm: "Gün boyunca · Açık stüdyo · Veranda",
      s: "Verandada tuval, boya ve fırçalar var. Beş dakika kal ya da bir saat.",
      b: "Bir tema ya da bitirme zorunluluğu yok. Bir iz bırakabilir, başka birinin başladığı resme devam edebilir ya da tuvalin başında yalnız kalabilirsin. Gün bittiğinde ortaya kimin yaptığı belli olmayan ortak işler çıkabilir.",
      w: 1760,
      hh: 2200,
    },
  ],
  en: [
    {
      i: "web/w2.webp",
      t: "Collective Sound",
      h: "Dr Oğuz Öner",
      m: "15:00–16:15 · 15 people",
      mm: "75 minutes · 15 people · House and surroundings",
      s: "First we listen to the island. Then we play what we heard with voice, breath and rhythm.",
      b: "What does Büyükada sound like? We will take a short sound walk around the house, listening to the wind, water, birds and one another. Then Dr Oğuz Öner will guide us through Soundpainting, weaving those sounds into a live, one-off composition. You do not need musical training—only a willingness to listen and make a sound.",
      w: 1080,
      hh: 1350,
    },
    {
      i: "web/w3.webp",
      t: "Fragrance Lab",
      h: "Şeyma Çavdur",
      m: "16:30–18:00 · 10 people",
      mm: "90 minutes · 10 people · Back garden",
      s: "From scent memory to perfume composition, with your own bottle to take home.",
      b: "With Şeyma Çavdur, we will look at how scent settles into memory, how the nose works and how a perfume is built. You will explore individual notes, map your own scent memory and compose a small fragrance of your own.",
      w: 1760,
      hh: 2200,
    },
    {
      i: "web/w5.webp",
      t: "Style Is Instinct",
      h: "Bisou Me",
      m: "18:00–19:00 · open entry",
      mm: "60 minutes · Open entry · Lawn",
      s: "What do the colours, textures and pieces you choose without thinking say about you?",
      b: "This is not a lesson in dressing correctly. Bisou Me invites you to make quick choices between images, textures and accessories, then notice what drew you in. You will turn that clue into one small intervention in your own look.",
      w: 800,
      hh: 600,
    },
    {
      i: "web/w6.webp",
      t: "Fortune Dome",
      h: "One-to-one experience",
      m: "16:30–17:30 · 21:15–22:15",
      mm: "15 minutes · One-to-one · Garden",
      s: "A small tent in the garden. We are not telling you what happens inside.",
      b: "Fortune Dome opens twice, once in daylight and once after dark. Choose a time from the list at the entrance and return when it is your turn. You go in alone. Those fifteen minutes are yours; you will discover the rest inside.",
      w: 1122,
      hh: 1402,
    },
    {
      i: "web/w7.webp",
      t: "Natural Dyeing",
      h: "Open studio",
      m: "All day · at your own pace",
      mm: "All day · Open studio · Garden",
      s: "Fold it, bind it, leave it in the dye. Let natural pigments have the final word.",
      b: "This open studio runs throughout the day. Choose your cloth and colours, then experiment with folding and binding before lowering your piece into the dye. The mark cannot be fully controlled—that is what makes each result singular.",
      w: 1760,
      hh: 2200,
    },
    {
      i: "web/w8.webp",
      t: "Free Painting",
      h: "Open studio",
      m: "All day · at your own pace",
      mm: "All day · Open studio · Veranda",
      s: "Canvas, paint and brushes are waiting on the veranda. Stay for five minutes or an hour.",
      b: "There is no theme and nothing has to be finished. Leave one mark, continue a painting somebody else began, or spend time alone with a canvas. By the end of the day, we may have works that belong to no single person.",
      w: 1760,
      hh: 2200,
    },
  ],
};
